name: Manual Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'lam version tag'
        required: true
        default: '7.4'
      latest:
        description: 'Is latest?'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Set env
      run: echo "LAM_RELEASE=${{ github.event.inputs.tags }}" >> $GITHUB_ENV
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image latest
      if: ${{ github.event.inputs.latest == 'yes' }}
      run: |
        docker buildx build \
          --tag carlesbarreda/lam:latest \
          --tag carlesbarreda/lam:$LAM_RELEASE \
          --build-arg LAM_RELEASE=$LAM_RELEASE \
          --platform linux/amd64,linux/arm64,linux/arm/v6 \
          --push \
          lam-packaging/docker

    - name: Build the Docker image
      if: ${{ github.event.inputs.latest != 'yes' }}
      run: |
        docker buildx build \
          --tag carlesbarreda/lam:$LAM_RELEASE \
          --build-arg LAM_RELEASE=$LAM_RELEASE \
          --platform linux/amd64,linux/arm64,linux/arm/v6 \
          --push \
          lam-packaging/docker
